name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name : checkout-code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    - name: git semantic version
      uses:  PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major: "
        minor_pattern: "feat: "
        format: "${major}.${minor}.${patch}-prereleases${increment}"
      id: version

    - name: docker-login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: build docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t seb4/graphql-actions:$NEW_VERSION .
        docker build -t seb4/graphql-actions:latest .
        
    - name: push docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
       docker push seb4/graphql-actions:$NEW_VERSION
       docker push seb4/graphql-actions:latest
       
