name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name : checkout-code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    - name: git semantic version
      uses:  PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major: "
        minor_pattern: "feat: "
        format: "${major}.${minor}.${patch}-prereleases${increment}"}
      id: version

        
      

    - name: docker-login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        NEW_VERSION: ${{steps.version.outputs.version}}
        
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "new version : $NEW_VERSION"
    
   # - name: build docker image
    #  run: |
    #    docker build -t seb4/graphql-actions:0.0.2 .
    #    docker build -t seb4/graphql-actions:latest .
        
    #- name: push docker image
    #  run: |
    #   docker push seb4/graphql-actions:0.0.2
    #   docker push seb4/graphql-actions:latest
       

    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    
